name: active_wrapper
version: 0.4.0
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://github.com/winton/active_wrapper
summary: Wraps ActiveRecord and Logger for use in non-Rails environments
description: Wraps ActiveRecord and Logger for use in non-Rails environments
dependencies:
  - activerecord
  - default:
    - mysql2
  - activerecord_2:
    - mysql
development_dependencies:
  - rake
  - rspec